import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  lui: {
    position: "absolute",
    width: 52,
    height: 52,
    left: 40,
    top: 44,
  },
  mailnut1: {
    position: "relative",
    width: "100%",
    flexDirection: "row",
    height: 50,
  },
  nut1: {
    position: "relative",
    width: "100%",
    height: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomColor: "#ABABAB",
    borderLeftColor: "#ABABAB",
    borderLeftWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightColor: "#ABABAB",
    borderTopColor: "#ABABAB",
    borderRightWidth: 0.5,
    borderTopWidth: 0.5,
    borderRadius: 8,
  },
  nutText1: {
    left: 40,
    fontSize: 19,
    fontWeight: "900",
    fontStyle: "normal",
    color: "#E94057",
  },
  imageContainer: {
    position: "absolute",
    width: "100%",
    height: 150,

    flexDirection: "row",
    justifyContent: "center",
    top: 250,
  },
  image: {
    left: 20,
    width: 100,
    height: 100,
    borderRadius: 25,
  },
  themif: {
    position: "absolute",
    width: "35%",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    height: 51,
    top: 150,
  },
  themiftext: {
    fontSize: 30,
    textAlign: "left",
    fontStyle: "normal",
    fontWeight: "700",
  },
  mailnut: {
    position: "absolute",
    width: "100%",
    bottom: 150,
    height: 56,

    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  nut: {
    width: "80%",
    height: 56,
    backgroundColor: "#E94057",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    marginTop: 20,
    borderRadius: 15,
  },
  nutText: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    fontSize: 19,
    fontWeight: "700",
    fontStyle: "normal",
    color: "white",
  },

  khunghinh: {
    position: "absolute",
    justifyContent: "center",
    fontSize: 35,
    alignItems: "center",
    flexDirection: "column",
    width: "80%",
    height: 58,

    top: 350,
  },
  khung: {
    margin: 20,
    flexDirection: "row",
    alignItems: "center",

    position: "relative",
    width: "100%",
    height: "100%",
    borderBottomColor: "#ABABAB",
    borderLeftColor: "#ABABAB",
    borderLeftWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightColor: "#ABABAB",
    borderTopColor: "#ABABAB",
    borderRightWidth: 0.5,
    borderTopWidth: 0.5,
    borderRadius: 8,
  },
  khung4: {
    marginBottom: 20,

    position: "relative",
    width: "100%",
    height: "100%",
    flexDirection: "row",
    alignItems: "center",
    borderBottomColor: "#ABABAB",
    borderLeftColor: "#ABABAB",
    borderLeftWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightColor: "#ABABAB",
    borderTopColor: "#ABABAB",
    borderRightWidth: 0.5,
    borderTopWidth: 0.5,
    borderRadius: 8,
  },

  MOBILEText: {
    fontSize: 16,
    color: "#E94057",
    fontWeight: "700",
  },
  MOBILE: {
    position: "absolute",
    flexDirection: "row",
    justifyContent: "flex-end",
    width: "90%",
    height: 24,
    top: 56,
  },
});
