import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  lui: {
    position: "absolute",
    width: 52,
    height: 52,
    left: 45,
    top: 44,
  },
  mailnut: {
    position: "absolute",
    width: "100%",
    bottom: 50,
    height: 56,

    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  nut: {
    width: "80%",
    height: 56,
    backgroundColor: "#E94057",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    marginTop: 20,
    borderRadius: 15,
  },
  nutText: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    fontSize: 19,
    fontWeight: "700",
    fontStyle: "normal",
    color: "white",
  },
  khung: {
    margin: 20,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 20,
    position: "relative",
    width: 140,
    height: 45,
    borderBottomColor: "#ABABAB",
    borderLeftColor: "#ABABAB",
    borderLeftWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightColor: "#ABABAB",
    borderTopColor: "#ABABAB",
    borderRightWidth: 0.5,
    borderTopWidth: 0.5,
    borderRadius: 8,
  },
  khungmau: {
    margin: 20,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 20,
    position: "relative",
    backgroundColor: "#E94057",
    width: 140,
    height: 45,
    borderBottomColor: "#ABABAB",
    borderLeftColor: "#ABABAB",
    borderLeftWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightColor: "#ABABAB",
    borderTopColor: "#ABABAB",
    borderRightWidth: 0.5,
    borderTopWidth: 0.5,
    borderRadius: 8,
  },
  Textsothich: {
    fontSize: 30,
    right: 25,
    marginLeft: 35,
    fontStyle: "normal",
    fontWeight: "700",
  },
  sothichText: {
    position: "absolute",
    width: "80%",
    justifyContent: "flex-start",
    alignItems: "center",
    flexDirection: "column",
    height: 70,
    top: 120,
  },
  textSkip: {
    fontSize: 16,
    color: "#E94057",
    fontWeight: "700",
  },
  Skiptext: {
    position: "absolute",
    flexDirection: "row",
    justifyContent: "flex-end",
    width: "90%",
    height: 24,
    top: 56,
  },
  imagelui: {
    position: "absolute",
    width: 52,
    height: 52,
    left: 40,
    top: 44,
  },
});
