import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  mailnut: {
    position: "absolute",
    width: "100%",
    top: 390,
    height: 56,

    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  nut: {
    width: "80%",
    height: 56,
    backgroundColor: "#E94057",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    marginTop: 20,
    borderRadius: 15,
  },
  nutText: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    fontSize: 19,
    fontWeight: "700",
    fontStyle: "normal",
    color: "white",
  },

  khunghinh: {
    position: "absolute",
    justifyContent: "space-around",
    alignItems: "center",
    flexDirection: "row",
    width: "80%",
    height: 58,

    top: 250,
  },
  khung: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    width: "15%",
    height: 50,
    borderBottomColor: "#E94057",
    borderLeftColor: "#E94057",
    borderLeftWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightColor: "#E94057",
    borderTopColor: "#E94057",
    borderRightWidth: 0.5,
    borderTopWidth: 0.5,
    borderRadius: 8,
  },
  khung4: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    width: "15%",
    height: 50,
    borderBottomColor: "#E94057",
    borderLeftColor: "#E94057",
    borderLeftWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightColor: "#E94057",
    borderTopColor: "#E94057",
    borderRightWidth: 0.5,
    borderTopWidth: 0.5,
    borderRadius: 8,
  },
  khung2: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    width: "15%",
    height: 50,
    borderBottomColor: "#E94057",
    borderLeftColor: "#E94057",
    borderLeftWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightColor: "#E94057",
    borderTopColor: "#E94057",
    borderRightWidth: 0.5,
    borderTopWidth: 0.5,
    borderRadius: 8,
  },
  khung3: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    width: "15%",
    height: 50,
    borderBottomColor: "#E94057",
    borderLeftColor: "#E94057",
    borderLeftWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightColor: "#E94057",
    borderTopColor: "#E94057",
    borderRightWidth: 0.5,
    borderTopWidth: 0.5,
    borderRadius: 8,
  },

  chitietsdt: {
    fontSize: 14,
    flexDirection: "row",
    justifyContent: "center",
    textAlign: "center",
    fontWeight: "400",

    fontStyle: "normal",
  },
  MOBILEText: {
    fontSize: 34,
    flexDirection: "row",
    justifyContent: "center",
    textAlign: "center",
    fontWeight: "700",
  },
  MOBILE: {
    position: "absolute",
    width: "80%",
    height: 93,
    left: 40,
    top: 128,
  },
});
