import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  containerr: {
    position: "absolute",

    width: 40,
    height: 40,
    top: 50,
  },
  khungmau: {
    marginRight: 5,
    marginTop: 5,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 5,
    position: "relative",
    backgroundColor: "#E94057",
    height: 35,
    borderBottomColor: "#ABABAB",
    borderLeftColor: "#ABABAB",
    borderLeftWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightColor: "#ABABAB",
    borderTopColor: "#ABABAB",
    borderRightWidth: 0.5,
    borderTopWidth: 0.5,
    borderRadius: 8,
  },
  containerrr: {
    position: "absolute",
    width: 50,
    height: 50,
  },
  containerrrrr: {
    width: 50,
    height: 50,
  },
  vitrii: {
    width: 80,
    right: 40,
    height: 42,
    top: 35,
    elevation: 10,
  },
  imagelui: {
    position: "absolute",
    width: 52,
    height: 52,
  },
  phuten: {
    width: "87%",
  },
  nhantin: {
    width: "15%",
    right: 30,
    height: 52,
    top: 35,
    elevation: 10,
  },
  mainten: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  nut2: {
    width: 80,
    height: 80,
    borderRadius: 50,
  },

  nut1: {
    width: 50,
    height: 50,
    borderRadius: 50,
    backgroundColor: "white",
    elevation: 10,
  },
  mainnut: {
    left: "7%",
    width: "85%",
    height: 70,
    position: "absolute",
    top: 435,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  mainnut2: {
    left: "4%",
    width: "100%",
    height: 70,
    position: "absolute",
    flexDirection: "row",
    justifyContent: "space-between",
    top: 30,
    opacity: 0.5,
  },
  mailchitiet: {
    width: "100%",
    height: 4000,
    position: "absolute",
    top: 470,
    backgroundColor: "white",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  ngaysinh: {
    fontSize: 20,
    left: 20,
    top: 30,
  },
  sothich: {
    fontSize: 20,
    left: 20,
    top: 30,
  },
  gioitinh: {
    fontSize: 16,
    left: 20,
    top: 30,
    opacity: 0.7,
  },
  diachi: {
    fontSize: 20,
    left: 20,
    top: 30,
  },
  diachi: {
    fontSize: 20,
    left: 20,
    top: 30,
    fontStyle: "normal",
  },
  ten: {
    fontSize: 25,
    left: 20,
    top: 30,
    fontStyle: "normal",
  },
  anh: {
    width: "100%",
    height: "100%",
  },
  mainanh: {
    width: "100%",
    height: "100%",
  },
  container: {
    width: "100%",
    height: 5000,
    backgroundColor: "white",
  },
});
