import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  mailnut: {
    position: "absolute",
    width: "100%",
    top: 145,
    height: 56,

    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  nut: {
    width: "100%",
    height: 56,
    backgroundColor: "#E94057",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    marginTop: 20,
    borderRadius: 15,
  },
  nutText: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    fontSize: 22,
    fontWeight: "700",
    fontStyle: "normal",
    color: "white",
  },

  mailnut1: {
    position: "absolute",
    width: "86%",
    bottom: 50,
    height: 50,
    left: "7%",
  },
  nut1: {
    width: "100%",
    height: 56,
    backgroundColor: "#ffffff",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    marginTop: 20,
    borderRadius: 15,
    borderBottomColor: "#ABABAB",
    borderLeftColor: "#ABABAB",
    borderLeftWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightColor: "#ABABAB",
    borderTopColor: "#ABABAB",
    borderRightWidth: 0.5,
    borderTopWidth: 0.5,
  },
  nutText1: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    fontSize: 22,
    fontWeight: "700",
    fontStyle: "normal",
    color: "#E94057",
  },

  khunghinh: {
    position: "absolute",
    justifyContent: "center",
    fontSize: 35,
    alignItems: "center",
    flexDirection: "column",
    width: "85%",
    marginLeft: 30,
    marginRight: 30,
    height: 50,

    top: 150,
  },
  khung: {
    margin: 20,

    paddingLeft: 20,
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
    width: "100%",
    height: "100%",
    borderBottomColor: "#ABABAB",
    borderLeftColor: "#ABABAB",
    borderLeftWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightColor: "#ABABAB",
    borderTopColor: "#ABABAB",
    borderRightWidth: 0.5,
    borderTopWidth: 0.5,
    borderRadius: 8,
  },
  khung1: {
    paddingLeft: 20,
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
    width: "100%",
    height: "100%",
    borderBottomColor: "#ABABAB",
    borderLeftColor: "#ABABAB",
    borderLeftWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightColor: "#ABABAB",
    borderTopColor: "#ABABAB",
    borderRightWidth: 0.5,
    borderTopWidth: 0.5,
    borderRadius: 8,
  },
  mainplanta: {
    justifyContent: "space-around",
    alignItems: "center",
    flexDirection: "row",
    marginTop: 100,
  },
  textplanta: {
    fontWeight: "700",
    fontSize: 50,
    textAlign: "center",
    color: "#ffffff",
  },

  mainchitiet: {
    justifyContent: "space-around",
    alignItems: "center",
    flexDirection: "row",
    marginTop: 0,

    marginLeft: 52,
    marginRight: 52,
  },
  chitiet: {
    fontSize: 16,
    textAlign: "center",
    opacity: 0.7,
    color: "#ffffff",
  },

  container: {
    position: "absolute",
    width: "100%",
    height: "35%",
    backgroundColor: "#E94057",
  },
});
